spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiry: 3600000
  refresh-token-expiry: 604800000